version: 2
project_name: panel

builds:
  - id: ace
    main: ./cmd/ace
    binary: ace
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w --extldflags "-static"
      - -X 'github.com/acepanel/panel/v3/internal/app.Version={{ .Version }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildTime={{ .Now.Format "2006-01-02 15:04:05 MST" }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.CommitHash={{ .ShortCommit }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.GoVersion={{ .Env.GOVERSION }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildID={{ .Env.GITHUB_RUN_ID }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildUser={{ .Env.USER }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildHost={{ .Env.HOSTNAME }}'
  - id: cli
    main: ./cmd/cli
    binary: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w --extldflags "-static"
      - -X 'github.com/acepanel/panel/v3/internal/app.Version={{ .Version }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildTime={{ .Now.Format "2006-01-02 15:04:05 MST" }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.CommitHash={{ .ShortCommit }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.GoVersion={{ .Env.GOVERSION }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildID={{ .Env.GITHUB_RUN_ID }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildUser={{ .Env.USER }}'
      - -X 'github.com/acepanel/panel/v3/internal/app.BuildHost={{ .Env.HOSTNAME }}'

archives:
  - id: panel
    ids:
      - ace
      - cli
    formats: ["zip"]
    wrap_in_directory: false
    strip_binary_directory: true
    files:
      - LICENSE
      - config.example.yml
      - storage/*
